# Generated by Django 5.2.2 on 2025-10-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='avtor',
            field=models.CharField(default=0, max_length=55, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
