# Generated by Django 5.2.2 on 2025-10-24 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_table_avtor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильм'},
        ),
    ]
