# Generated by Django 5.2.2 on 2025-10-31 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_table_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='avtor',
        ),
    ]
